version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: klaro_postgres_new
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - klaro_new_data:/var/lib/postgresql/data

volumes:
  klaro_new_data: